name = "Mandelbrot"
uuid = "99c3bb84-eb93-41a8-a08c-71271022a403"
authors = ["vasanth <vasanth.mani.vasi.2@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
